### PR TITLE
Handle SGR 38/48

### PR DESCRIPTION
**Pull request by thentenaar**
Hi Kevin,

Here's another PR. :)

Granted I'd love to have support for higher color modes in Linux / Xterm mode, I wanted to also ask what your thoughts are on the subject, and whether or not you see that as something you'd also like to see in Qodem. 

At least with this patch, those color sequences won't cause the entire terminal to be underlined and blinking when I use vim. ;)

### CODE REVIEW

**Comment by klamonte** [comment]
Hi Tim,

Thanks for the patch!  I've incorporated autogen, and aclocal, ccc is in with some additional comments.

On the SGR 38/48, it would be non-trivial to really support in Qodem right now.  The biggest hurdle is that ncurses and PDcurses don't have RGB support.  (The win32a PDcurses does, but it's non-standard.)  Beyond that the xterm/konsole/gnome-terminal people haven't fully settled on turning the same sequences into the same colors on screen.  What I did do though was have XTERM / XTERM_UTF8 recognize 38/48 and discard the entire sequence, which keeps a clean display.  (The other emulations (VT10x/220/Linux) will still behave the way they "should" which is what you saw before: blinking and sometimes underlined.)

**Comment by klamonte** [comment]
(BTW still getting used to shared github.  Probably should have tried pulling on your branch first. :( )

**Comment by thentenaar** [comment]
Awesome, thanks for integrating those. :)

Btw, Linux [doesn't](https://github.com/torvalds/linux/commit/e05ab238e30572abbac0cc4aba051553928de949#diff-7da3c215d12c9f6b88e1a37d38b116f0R1393) set underline for SGR 38, at least not anymore. :)

The return there is fine, but IMHO incrementing `i` there allows skipping the SGR sequence in question while still processing other codes that may follow it (AFAIR you can chain any number of such codes separated by semicolon.) But, I'm not an expert, and don't happen to have the manual handy. :P

IMHO, the trick with indexed colors is that you have enough color pairs, and to find a way to store the state needed to render the buffer without needing 3x or 4x more memory; and having a way to degrade gracefully when the terminal we're running in doesn't support it at all. :)

I did make use of some of the "extended" color stuff in [a small program]( https://github.com/thentenaar/tp2/blob/master/src/ui.c#L148) and I was able to get decent results; but I didn't need too many colors at a time. :) It uses "RGB" style colors (if supported) and indexed colors, a la xterm, as a fallback. Provided your terminal has the _initc_ and _ccc_ caps, it should be possible with ncurses; but yes, the results may very well be terminal-dependent, and if so there'd be no way to cover literally every edge-case. But for that particular case, I had pretty good results with PDCurses for DOS, though I didn't try it with the X11 PDCurses.

WRT git, you could also use 'git rebase' to rebase the commits on top of your master branch (since it can be fast-forwarded), assuming you don't want to cherry-pick them one-by-one. If you intended to preserve the commits, assuming you have my branch available in your repo you can still do:
```
(on master)
git reset --hard 472385fae9a643a1d0343322d86fb968f712bb66
git rebase -p handle_sgr_38_48
git cherry-pick bdc503be3feac502c1d09ebbd3efeba25d657ecb
(fix conflicts, then do a git add on each conflicting file)
git cherry-pick --continue
git show HEAD (to verify that the changes in the conflicting commit are as intended)
git push -f origin master
```

**Comment by klamonte** [comment]
1.0.0-dev is merged to master, closing this one.

**Pull request closed without merging**
